# .goreleaser.yaml
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: herd
    main: ./cmd/herd
    binary: herd
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/herd-core/herd/internal/config.Version={{.Version}}

  - id: herd-guest-agent
    main: ./cmd/herd-guest-agent
    binary: herd-guest-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: herd-core
    name: herd
  extra_files:
    - glob: assets/vmlinux-v6.1.bin
