//go:build linux

// seccomp_linux.go — seccomp BPF syscall filter for herd workers.
//
// # Overview
//
// Seccomp (Secure Computing mode) restricts which syscalls a process can
// invoke. Herd uses an allowlist: the worker process is permitted only the
// syscalls a typical HTTP server needs. Every other syscall returns EPERM
// (SeccompPolicyErrno) or kills the process (SeccompPolicyKill).
//
// # Threading note
//
// Go multiplexes goroutines onto OS threads (M:N model). The BPF filter must
// be installed with SECCOMP_FILTER_FLAG_TSYNC so it is applied to all OS
// threads the Go runtime creates — not just the one that called the syscall.
// go-seccomp-bpf handles this automatically.
//
// # Worker integration
//
// [ProcessFactory] injects HERD_SECCOMP_PROFILE into the worker's environment.
// The worker binary calls [EnterSandbox] at the top of main() to install the
// filter. This design keeps the filter in the child process and avoids
// contaminating the herd parent process.
package herd

import (
	"fmt"
	"os"

	seccomp "github.com/elastic/go-seccomp-bpf"
	"golang.org/x/net/bpf"
)

// SeccompPolicy controls how unauthorized syscalls are handled.
type SeccompPolicy int

const (
	// SeccompPolicyOff disables seccomp filtering entirely.
	// Workers that do not call EnterSandbox should use this policy.
	SeccompPolicyOff SeccompPolicy = iota

	// SeccompPolicyLog logs blocked syscalls via the kernel audit subsystem
	// but does not block them. Requires Linux 4.14+. Useful during development
	// to discover which syscalls a new worker needs.
	SeccompPolicyLog

	// SeccompPolicyErrno returns EPERM for any unauthorized syscall.
	// This is the default for production workers.
	SeccompPolicyErrno

	// SeccompPolicyKill terminates the process immediately on any unauthorized
	// syscall. Strictest policy; no error is returned to the caller.
	SeccompPolicyKill
)

// envValue returns the string written into HERD_SECCOMP_PROFILE.
func (p SeccompPolicy) envValue() string {
	switch p {
	case SeccompPolicyLog:
		return "log"
	case SeccompPolicyErrno:
		return "errno"
	case SeccompPolicyKill:
		return "kill"
	default:
		return "off"
	}
}

// parsePolicyEnv converts the HERD_SECCOMP_PROFILE value back to a SeccompPolicy.
func parsePolicyEnv(s string) SeccompPolicy {
	switch s {
	case "log":
		return SeccompPolicyLog
	case "errno":
		return SeccompPolicyErrno
	case "kill":
		return SeccompPolicyKill
	default:
		return SeccompPolicyOff
	}
}

// defaultSeccompAction maps a SeccompPolicy to a go-seccomp-bpf Action.
func defaultSeccompAction(p SeccompPolicy) seccomp.Action {
	switch p {
	case SeccompPolicyLog:
		return seccomp.ActionLog
	case SeccompPolicyKill:
		return seccomp.ActionKillProcess
	default: // SeccompPolicyErrno
		return seccomp.ActionErrno
	}
}

// httpWorkerSyscalls is the allowlist for a typical HTTP server process.
// Generated by combining:
//   - Docker's default seccomp profile (moby/moby)
//   - Go runtime syscall requirements (strace on a minimal Go HTTP server)
//   - Playwright/Chromium additional requirements removed (use WithSeccompPolicy(SeccompPolicyOff))
//
// Missing a syscall? Run strace -f -e trace=all on your worker and add
// any blocked-but-needed calls via WithSeccompPolicy or a custom policy.
var httpWorkerSyscalls = []string{
	// ---- File I/O ----
	"read", "write", "readv", "writev",
	"pread64", "pwrite64", "sendfile",
	"open", "openat", "openat2", "creat",
	"close", "close_range",
	"stat", "fstat", "lstat", "newfstatat",
	"statx", "statfs", "fstatfs",
	"lseek", "dup", "dup2", "dup3",
	"fcntl", "ioctl",
	"access", "faccessat", "faccessat2",
	"readlink", "readlinkat",
	"getcwd", "chdir", "fchdir",
	"mkdir", "mkdirat", "rmdir",
	"unlink", "unlinkat",
	"rename", "renameat", "renameat2",
	"chmod", "fchmod", "fchmodat",
	"chown", "fchown", "lchown", "fchownat",
	"truncate", "ftruncate",
	"link", "linkat", "symlink", "symlinkat",
	"sync", "fsync", "fdatasync", "syncfs",
	"getdents", "getdents64",

	// ---- Networking ----
	"socket", "bind", "listen",
	"accept", "accept4",
	"connect",
	"sendto", "recvfrom",
	"sendmsg", "recvmsg",
	"sendmmsg", "recvmmsg",
	"setsockopt", "getsockopt",
	"getsockname", "getpeername",
	"socketpair", "shutdown",

	// ---- Memory management ----
	"mmap", "munmap", "mprotect",
	"madvise", "brk",
	"mremap", "msync",
	"mincore", "mlock", "mlock2", "munlock",
	"mlockall", "munlockall",
	"mbind", "set_mempolicy", "get_mempolicy",

	// ---- Polling & I/O multiplexing ----
	"poll", "ppoll",
	"select", "pselect6",
	"epoll_create", "epoll_create1",
	"epoll_ctl", "epoll_wait", "epoll_pwait", "epoll_pwait2",
	"pipe", "pipe2",
	"eventfd", "eventfd2",
	"timerfd_create", "timerfd_settime", "timerfd_gettime",
	"inotify_init", "inotify_init1",
	"inotify_add_watch", "inotify_rm_watch",
	"signalfd", "signalfd4",

	// ---- Go runtime — threading ----
	// clone is allowed but argument filtering restricts it to thread-creation
	// flags only (CLONE_THREAD | CLONE_VM | CLONE_FILES | CLONE_SIGHAND).
	// Fork-style clones (creating new processes) are unnecessary for workers.
	"clone", "clone3",
	"futex", "futex_waitv",
	"set_robust_list", "get_robust_list",
	"tkill", "tgkill",
	"sched_yield",
	"sched_getaffinity", "sched_setaffinity",
	"sched_getparam", "sched_setparam",
	"sched_getscheduler", "sched_setscheduler",

	// ---- Signals ----
	"rt_sigaction", "rt_sigreturn",
	"rt_sigprocmask", "rt_sigsuspend",
	"rt_sigpending", "rt_sigtimedwait",
	"rt_sigqueueinfo", "rt_tgsigqueueinfo",
	"sigaltstack", "kill", "pause",

	// ---- Process info ----
	"getpid", "getppid", "gettid",
	"getuid", "getgid", "geteuid", "getegid",
	"getgroups",
	"getpgrp", "getpgid", "getsid",
	"getrlimit", "setrlimit", "prlimit64",
	"getrusage",
	"uname", "sysinfo",

	// ---- Time ----
	"clock_gettime", "clock_getres", "clock_nanosleep",
	"gettimeofday", "settimeofday",
	"nanosleep", "time", "times",
	"adjtimex", "clock_adjtime",

	// ---- Exit ----
	"exit", "exit_group",
	"wait4", "waitid", "waitpid",

	// ---- Misc Go runtime ----
	"arch_prctl",          // set thread-local storage (x86-64)
	"set_tid_address",     // Go runtime init
	"restart_syscall",     // signal restart
	"getrandom",           // crypto/rand
	"rseq",                // restartable sequences (Go 1.21+)
	"membarrier",          // Go runtime memory barrier
	"prctl",               // Go runtime uses PR_SET_NAME etc.

	// ---- Misc ----
	"capget",              // reading own capabilities is harmless
	"syslog",              // some logging frameworks use it
	"umask",
}

// EnterSandbox installs the seccomp syscall filter for the current process.
// Worker binaries should call this at the very top of main(), before starting
// any goroutines or HTTP servers.
//
// The filter policy is read from the HERD_SECCOMP_PROFILE environment variable,
// which [ProcessFactory] injects automatically. If the variable is absent or
// set to "off", EnterSandbox is a no-op.
//
// EnterSandbox installs the filter with SECCOMP_FILTER_FLAG_TSYNC, which
// synchronises the filter across all OS threads created by the Go runtime.
//
// Example worker main():
//
//	func main() {
//	    if err := herd.EnterSandbox(); err != nil {
//	        log.Fatalf("seccomp: %v", err)
//	    }
//	    // ... start HTTP server ...
//	}
func EnterSandbox() error {
	profileEnv := os.Getenv("HERD_SECCOMP_PROFILE")
	if profileEnv == "" || profileEnv == "off" {
		return nil
	}

	policy := parsePolicyEnv(profileEnv)
	if policy == SeccompPolicyOff {
		return nil
	}

	filter := seccomp.Filter{
		NoNewPrivs: true, // belt-and-suspenders: also set by SysProcAttr in parent
		Flag:       seccomp.FilterFlagTSync,
		Policy: seccomp.Policy{
			DefaultAction: defaultSeccompAction(policy),
			Syscalls: []seccomp.SyscallGroup{
				{
					Action: seccomp.ActionAllow,
					Names:  httpWorkerSyscalls,
				},
			},
		},
	}

	if err := seccomp.LoadFilter(filter); err != nil {
		return fmt.Errorf("herd: EnterSandbox: load seccomp filter: %w", err)
	}
	return nil
}

// buildHTTPWorkerFilter builds but does not install the BPF filter for the
// http-worker policy. Used in tests to validate the BPF program structure.
func buildHTTPWorkerFilter(policy SeccompPolicy) ([]bpf.Instruction, error) {
	f := seccomp.Filter{
		NoNewPrivs: false,
		Flag:       seccomp.FilterFlagTSync,
		Policy: seccomp.Policy{
			DefaultAction: defaultSeccompAction(policy),
			Syscalls: []seccomp.SyscallGroup{
				{
					Action: seccomp.ActionAllow,
					Names:  httpWorkerSyscalls,
				},
			},
		},
	}
	return f.Policy.Assemble()
}
