// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/herd/v1/herd.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_REQUEST_TYPE_UNSPECIFIED RequestType = 0
	RequestType_REQUEST_TYPE_ACQUIRE     RequestType = 1
	RequestType_REQUEST_TYPE_PING        RequestType = 2
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "REQUEST_TYPE_UNSPECIFIED",
		1: "REQUEST_TYPE_ACQUIRE",
		2: "REQUEST_TYPE_PING",
	}
	RequestType_value = map[string]int32{
		"REQUEST_TYPE_UNSPECIFIED": 0,
		"REQUEST_TYPE_ACQUIRE":     1,
		"REQUEST_TYPE_PING":        2,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_herd_v1_herd_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_proto_herd_v1_herd_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_proto_herd_v1_herd_proto_rawDescGZIP(), []int{0}
}

type AcquireRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional tags to route to specific worker pools (e.g., "python", "image-inference")
	WorkerType string `protobuf:"bytes,1,opt,name=worker_type,json=workerType,proto3" json:"worker_type,omitempty"`
	// Timeout in seconds before giving up on acquiring
	TimeoutSeconds int32 `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// Optional sessions id which would be used during accidental sessions drops
	SessionId *string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	// The type of request (ACQUIRE for initial lease, PING for heartbeats)
	Type          RequestType `protobuf:"varint,4,opt,name=type,proto3,enum=herd.v1.RequestType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_proto_herd_v1_herd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_herd_v1_herd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_proto_herd_v1_herd_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireRequest) GetWorkerType() string {
	if x != nil {
		return x.WorkerType
	}
	return ""
}

func (x *AcquireRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *AcquireRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *AcquireRequest) GetType() RequestType {
	if x != nil {
		return x.Type
	}
	return RequestType_REQUEST_TYPE_UNSPECIFIED
}

type AcquireResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Unique Session ID allocated
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The Local HTTP Address of the reverse proxy representing that worker
	ProxyAddress string `protobuf:"bytes,2,opt,name=proxy_address,json=proxyAddress,proto3" json:"proxy_address,omitempty"`
	// The local Worker Pid (optional for debugging/inspecting)
	WorkerPid     int32 `protobuf:"varint,3,opt,name=worker_pid,json=workerPid,proto3" json:"worker_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	mi := &file_proto_herd_v1_herd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_herd_v1_herd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_proto_herd_v1_herd_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AcquireResponse) GetProxyAddress() string {
	if x != nil {
		return x.ProxyAddress
	}
	return ""
}

func (x *AcquireResponse) GetWorkerPid() int32 {
	if x != nil {
		return x.WorkerPid
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkers int32                  `protobuf:"varint,1,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	IdleWorkers   int32                  `protobuf:"varint,2,opt,name=idle_workers,json=idleWorkers,proto3" json:"idle_workers,omitempty"`
	MaxWorkers    int32                  `protobuf:"varint,3,opt,name=max_workers,json=maxWorkers,proto3" json:"max_workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_herd_v1_herd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_herd_v1_herd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_herd_v1_herd_proto_rawDescGZIP(), []int{2}
}

func (x *StatusResponse) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *StatusResponse) GetIdleWorkers() int32 {
	if x != nil {
		return x.IdleWorkers
	}
	return 0
}

func (x *StatusResponse) GetMaxWorkers() int32 {
	if x != nil {
		return x.MaxWorkers
	}
	return 0
}

var File_proto_herd_v1_herd_proto protoreflect.FileDescriptor

const file_proto_herd_v1_herd_proto_rawDesc = "" +
	"\n" +
	"\x18proto/herd/v1/herd.proto\x12\aherd.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x01\n" +
	"\x0eAcquireRequest\x12\x1f\n" +
	"\vworker_type\x18\x01 \x01(\tR\n" +
	"workerType\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\x12\"\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.herd.v1.RequestTypeR\x04typeB\r\n" +
	"\v_session_id\"t\n" +
	"\x0fAcquireResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rproxy_address\x18\x02 \x01(\tR\fproxyAddress\x12\x1d\n" +
	"\n" +
	"worker_pid\x18\x03 \x01(\x05R\tworkerPid\"{\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0eactive_workers\x18\x01 \x01(\x05R\ractiveWorkers\x12!\n" +
	"\fidle_workers\x18\x02 \x01(\x05R\vidleWorkers\x12\x1f\n" +
	"\vmax_workers\x18\x03 \x01(\x05R\n" +
	"maxWorkers*\\\n" +
	"\vRequestType\x12\x1c\n" +
	"\x18REQUEST_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REQUEST_TYPE_ACQUIRE\x10\x01\x12\x15\n" +
	"\x11REQUEST_TYPE_PING\x10\x022\x8a\x01\n" +
	"\vHerdService\x12@\n" +
	"\aAcquire\x12\x17.herd.v1.AcquireRequest\x1a\x18.herd.v1.AcquireResponse(\x010\x01\x129\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.herd.v1.StatusResponseB)Z'github.com/herd-core/herd/proto/herd/v1b\x06proto3"

var (
	file_proto_herd_v1_herd_proto_rawDescOnce sync.Once
	file_proto_herd_v1_herd_proto_rawDescData []byte
)

func file_proto_herd_v1_herd_proto_rawDescGZIP() []byte {
	file_proto_herd_v1_herd_proto_rawDescOnce.Do(func() {
		file_proto_herd_v1_herd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_herd_v1_herd_proto_rawDesc), len(file_proto_herd_v1_herd_proto_rawDesc)))
	})
	return file_proto_herd_v1_herd_proto_rawDescData
}

var file_proto_herd_v1_herd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_herd_v1_herd_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_herd_v1_herd_proto_goTypes = []any{
	(RequestType)(0),        // 0: herd.v1.RequestType
	(*AcquireRequest)(nil),  // 1: herd.v1.AcquireRequest
	(*AcquireResponse)(nil), // 2: herd.v1.AcquireResponse
	(*StatusResponse)(nil),  // 3: herd.v1.StatusResponse
	(*emptypb.Empty)(nil),   // 4: google.protobuf.Empty
}
var file_proto_herd_v1_herd_proto_depIdxs = []int32{
	0, // 0: herd.v1.AcquireRequest.type:type_name -> herd.v1.RequestType
	1, // 1: herd.v1.HerdService.Acquire:input_type -> herd.v1.AcquireRequest
	4, // 2: herd.v1.HerdService.Status:input_type -> google.protobuf.Empty
	2, // 3: herd.v1.HerdService.Acquire:output_type -> herd.v1.AcquireResponse
	3, // 4: herd.v1.HerdService.Status:output_type -> herd.v1.StatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_herd_v1_herd_proto_init() }
func file_proto_herd_v1_herd_proto_init() {
	if File_proto_herd_v1_herd_proto != nil {
		return
	}
	file_proto_herd_v1_herd_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_herd_v1_herd_proto_rawDesc), len(file_proto_herd_v1_herd_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_herd_v1_herd_proto_goTypes,
		DependencyIndexes: file_proto_herd_v1_herd_proto_depIdxs,
		EnumInfos:         file_proto_herd_v1_herd_proto_enumTypes,
		MessageInfos:      file_proto_herd_v1_herd_proto_msgTypes,
	}.Build()
	File_proto_herd_v1_herd_proto = out.File
	file_proto_herd_v1_herd_proto_goTypes = nil
	file_proto_herd_v1_herd_proto_depIdxs = nil
}
