// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/herd/v1/herd.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HerdService_Acquire_FullMethodName = "/herd.v1.HerdService/Acquire"
	HerdService_Status_FullMethodName  = "/herd.v1.HerdService/Status"
)

// HerdServiceClient is the client API for HerdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HerdService manages connection-backed process allocation over gRPC.
type HerdServiceClient interface {
	// Acquire a worker slot. Holds the bidirectional stream open to maintain the lock.
	// If the stream breaks (EOF), the daemon triggers an auto-release of the worker.
	Acquire(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AcquireRequest, AcquireResponse], error)
	// Status checks daemon and pool health (Active vs Free workers).
	Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
}

type herdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHerdServiceClient(cc grpc.ClientConnInterface) HerdServiceClient {
	return &herdServiceClient{cc}
}

func (c *herdServiceClient) Acquire(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AcquireRequest, AcquireResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HerdService_ServiceDesc.Streams[0], HerdService_Acquire_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AcquireRequest, AcquireResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdService_AcquireClient = grpc.BidiStreamingClient[AcquireRequest, AcquireResponse]

func (c *herdServiceClient) Status(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, HerdService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HerdServiceServer is the server API for HerdService service.
// All implementations must embed UnimplementedHerdServiceServer
// for forward compatibility.
//
// HerdService manages connection-backed process allocation over gRPC.
type HerdServiceServer interface {
	// Acquire a worker slot. Holds the bidirectional stream open to maintain the lock.
	// If the stream breaks (EOF), the daemon triggers an auto-release of the worker.
	Acquire(grpc.BidiStreamingServer[AcquireRequest, AcquireResponse]) error
	// Status checks daemon and pool health (Active vs Free workers).
	Status(context.Context, *emptypb.Empty) (*StatusResponse, error)
	mustEmbedUnimplementedHerdServiceServer()
}

// UnimplementedHerdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHerdServiceServer struct{}

func (UnimplementedHerdServiceServer) Acquire(grpc.BidiStreamingServer[AcquireRequest, AcquireResponse]) error {
	return status.Error(codes.Unimplemented, "method Acquire not implemented")
}
func (UnimplementedHerdServiceServer) Status(context.Context, *emptypb.Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedHerdServiceServer) mustEmbedUnimplementedHerdServiceServer() {}
func (UnimplementedHerdServiceServer) testEmbeddedByValue()                     {}

// UnsafeHerdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HerdServiceServer will
// result in compilation errors.
type UnsafeHerdServiceServer interface {
	mustEmbedUnimplementedHerdServiceServer()
}

func RegisterHerdServiceServer(s grpc.ServiceRegistrar, srv HerdServiceServer) {
	// If the following call panics, it indicates UnimplementedHerdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HerdService_ServiceDesc, srv)
}

func _HerdService_Acquire_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HerdServiceServer).Acquire(&grpc.GenericServerStream[AcquireRequest, AcquireResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdService_AcquireServer = grpc.BidiStreamingServer[AcquireRequest, AcquireResponse]

func _HerdService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HerdServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HerdService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HerdServiceServer).Status(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// HerdService_ServiceDesc is the grpc.ServiceDesc for HerdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HerdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "herd.v1.HerdService",
	HandlerType: (*HerdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _HerdService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Acquire",
			Handler:       _HerdService_Acquire_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/herd/v1/herd.proto",
}
