# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: herd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'herd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nherd.proto\x12\x07herd.v1\x1a\x1bgoogle/protobuf/empty.proto\">\n\x0e\x41\x63quireRequest\x12\x13\n\x0bworker_type\x18\x01 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x02 \x01(\x05\"P\n\x0f\x41\x63quireResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\rproxy_address\x18\x02 \x01(\t\x12\x12\n\nworker_pid\x18\x03 \x01(\x05\"S\n\x0eStatusResponse\x12\x16\n\x0e\x61\x63tive_workers\x18\x01 \x01(\x05\x12\x14\n\x0cidle_workers\x18\x02 \x01(\x05\x12\x13\n\x0bmax_workers\x18\x03 \x01(\x05\x32\x8a\x01\n\x0bHerdService\x12@\n\x07\x41\x63quire\x12\x17.herd.v1.AcquireRequest\x1a\x18.herd.v1.AcquireResponse(\x01\x30\x01\x12\x39\n\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.herd.v1.StatusResponseB)Z\'github.com/herd-core/herd/proto/herd/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'herd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/herd-core/herd/proto/herd/v1'
  _globals['_ACQUIREREQUEST']._serialized_start=52
  _globals['_ACQUIREREQUEST']._serialized_end=114
  _globals['_ACQUIRERESPONSE']._serialized_start=116
  _globals['_ACQUIRERESPONSE']._serialized_end=196
  _globals['_STATUSRESPONSE']._serialized_start=198
  _globals['_STATUSRESPONSE']._serialized_end=281
  _globals['_HERDSERVICE']._serialized_start=284
  _globals['_HERDSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
