# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import herd_pb2 as herd__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in herd_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HerdServiceStub(object):
    """HerdService manages connection-backed process allocation over gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Acquire = channel.stream_stream(
                '/herd.v1.HerdService/Acquire',
                request_serializer=herd__pb2.AcquireRequest.SerializeToString,
                response_deserializer=herd__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/herd.v1.HerdService/Status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=herd__pb2.StatusResponse.FromString,
                _registered_method=True)


class HerdServiceServicer(object):
    """HerdService manages connection-backed process allocation over gRPC.
    """

    def Acquire(self, request_iterator, context):
        """Acquire a worker slot. Holds the bidirectional stream open to maintain the lock.
        If the stream breaks (EOF), the daemon triggers an auto-release of the worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status checks daemon and pool health (Active vs Free workers).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HerdServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Acquire': grpc.stream_stream_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=herd__pb2.AcquireRequest.FromString,
                    response_serializer=herd__pb2.AcquireResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=herd__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'herd.v1.HerdService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('herd.v1.HerdService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HerdService(object):
    """HerdService manages connection-backed process allocation over gRPC.
    """

    @staticmethod
    def Acquire(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/herd.v1.HerdService/Acquire',
            herd__pb2.AcquireRequest.SerializeToString,
            herd__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/herd.v1.HerdService/Status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            herd__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
