// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: internal/proto/v1/herd.proto

package herdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStream struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AvailableMemoryMb int64                  `protobuf:"varint,2,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	ActiveVmCount     int32                  `protobuf:"varint,3,opt,name=active_vm_count,json=activeVmCount,proto3" json:"active_vm_count,omitempty"`
	CpuUsagePercent   float64                `protobuf:"fixed64,4,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	InterfaceIp       string                 `protobuf:"bytes,6,opt,name=interface_ip,json=interfaceIp,proto3" json:"interface_ip,omitempty"`
	ActiveSessions    []*SessionInfo         `protobuf:"bytes,7,rep,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NodeStream) Reset() {
	*x = NodeStream{}
	mi := &file_internal_proto_v1_herd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStream) ProtoMessage() {}

func (x *NodeStream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_herd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStream.ProtoReflect.Descriptor instead.
func (*NodeStream) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_herd_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStream) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStream) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *NodeStream) GetActiveVmCount() int32 {
	if x != nil {
		return x.ActiveVmCount
	}
	return 0
}

func (x *NodeStream) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeStream) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *NodeStream) GetInterfaceIp() string {
	if x != nil {
		return x.InterfaceIp
	}
	return ""
}

func (x *NodeStream) GetActiveSessions() []*SessionInfo {
	if x != nil {
		return x.ActiveSessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_internal_proto_v1_herd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_herd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_herd_proto_rawDescGZIP(), []int{1}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CloudCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // "boot_vm", "destroy_vm", etc.
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudCommand) Reset() {
	*x = CloudCommand{}
	mi := &file_internal_proto_v1_herd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudCommand) ProtoMessage() {}

func (x *CloudCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_v1_herd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudCommand.ProtoReflect.Descriptor instead.
func (*CloudCommand) Descriptor() ([]byte, []int) {
	return file_internal_proto_v1_herd_proto_rawDescGZIP(), []int{2}
}

func (x *CloudCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CloudCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CloudCommand) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_internal_proto_v1_herd_proto protoreflect.FileDescriptor

const file_internal_proto_v1_herd_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/proto/v1/herd.proto\x12\aherd.v1\"\xb2\x02\n" +
	"\n" +
	"NodeStream\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12.\n" +
	"\x13available_memory_mb\x18\x02 \x01(\x03R\x11availableMemoryMb\x12&\n" +
	"\x0factive_vm_count\x18\x03 \x01(\x05R\ractiveVmCount\x12*\n" +
	"\x11cpu_usage_percent\x18\x04 \x01(\x01R\x0fcpuUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\finterface_ip\x18\x06 \x01(\tR\vinterfaceIp\x12=\n" +
	"\x0factive_sessions\x18\a \x03(\v2\x14.herd.v1.SessionInfoR\x0eactiveSessions\"@\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xbb\x01\n" +
	"\fCloudCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x129\n" +
	"\x06params\x18\x03 \x03(\v2!.herd.v1.CloudCommand.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012M\n" +
	"\x10HerdControlPlane\x129\n" +
	"\aConnect\x12\x13.herd.v1.NodeStream\x1a\x15.herd.v1.CloudCommand(\x010\x01B4Z2github.com/herd-core/herd/internal/proto/v1;herdv1b\x06proto3"

var (
	file_internal_proto_v1_herd_proto_rawDescOnce sync.Once
	file_internal_proto_v1_herd_proto_rawDescData []byte
)

func file_internal_proto_v1_herd_proto_rawDescGZIP() []byte {
	file_internal_proto_v1_herd_proto_rawDescOnce.Do(func() {
		file_internal_proto_v1_herd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_v1_herd_proto_rawDesc), len(file_internal_proto_v1_herd_proto_rawDesc)))
	})
	return file_internal_proto_v1_herd_proto_rawDescData
}

var file_internal_proto_v1_herd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_proto_v1_herd_proto_goTypes = []any{
	(*NodeStream)(nil),   // 0: herd.v1.NodeStream
	(*SessionInfo)(nil),  // 1: herd.v1.SessionInfo
	(*CloudCommand)(nil), // 2: herd.v1.CloudCommand
	nil,                  // 3: herd.v1.CloudCommand.ParamsEntry
}
var file_internal_proto_v1_herd_proto_depIdxs = []int32{
	1, // 0: herd.v1.NodeStream.active_sessions:type_name -> herd.v1.SessionInfo
	3, // 1: herd.v1.CloudCommand.params:type_name -> herd.v1.CloudCommand.ParamsEntry
	0, // 2: herd.v1.HerdControlPlane.Connect:input_type -> herd.v1.NodeStream
	2, // 3: herd.v1.HerdControlPlane.Connect:output_type -> herd.v1.CloudCommand
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_v1_herd_proto_init() }
func file_internal_proto_v1_herd_proto_init() {
	if File_internal_proto_v1_herd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_v1_herd_proto_rawDesc), len(file_internal_proto_v1_herd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_v1_herd_proto_goTypes,
		DependencyIndexes: file_internal_proto_v1_herd_proto_depIdxs,
		MessageInfos:      file_internal_proto_v1_herd_proto_msgTypes,
	}.Build()
	File_internal_proto_v1_herd_proto = out.File
	file_internal_proto_v1_herd_proto_goTypes = nil
	file_internal_proto_v1_herd_proto_depIdxs = nil
}
