// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/proto/v1/herd.proto

package herdv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HerdControlPlane_Connect_FullMethodName = "/herd.v1.HerdControlPlane/Connect"
)

// HerdControlPlaneClient is the client API for HerdControlPlane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HerdControlPlaneClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeStream, CloudCommand], error)
}

type herdControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewHerdControlPlaneClient(cc grpc.ClientConnInterface) HerdControlPlaneClient {
	return &herdControlPlaneClient{cc}
}

func (c *herdControlPlaneClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeStream, CloudCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HerdControlPlane_ServiceDesc.Streams[0], HerdControlPlane_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeStream, CloudCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdControlPlane_ConnectClient = grpc.BidiStreamingClient[NodeStream, CloudCommand]

// HerdControlPlaneServer is the server API for HerdControlPlane service.
// All implementations must embed UnimplementedHerdControlPlaneServer
// for forward compatibility.
type HerdControlPlaneServer interface {
	Connect(grpc.BidiStreamingServer[NodeStream, CloudCommand]) error
	mustEmbedUnimplementedHerdControlPlaneServer()
}

// UnimplementedHerdControlPlaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHerdControlPlaneServer struct{}

func (UnimplementedHerdControlPlaneServer) Connect(grpc.BidiStreamingServer[NodeStream, CloudCommand]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHerdControlPlaneServer) mustEmbedUnimplementedHerdControlPlaneServer() {}
func (UnimplementedHerdControlPlaneServer) testEmbeddedByValue()                          {}

// UnsafeHerdControlPlaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HerdControlPlaneServer will
// result in compilation errors.
type UnsafeHerdControlPlaneServer interface {
	mustEmbedUnimplementedHerdControlPlaneServer()
}

func RegisterHerdControlPlaneServer(s grpc.ServiceRegistrar, srv HerdControlPlaneServer) {
	// If the following call panics, it indicates UnimplementedHerdControlPlaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HerdControlPlane_ServiceDesc, srv)
}

func _HerdControlPlane_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HerdControlPlaneServer).Connect(&grpc.GenericServerStream[NodeStream, CloudCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HerdControlPlane_ConnectServer = grpc.BidiStreamingServer[NodeStream, CloudCommand]

// HerdControlPlane_ServiceDesc is the grpc.ServiceDesc for HerdControlPlane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HerdControlPlane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "herd.v1.HerdControlPlane",
	HandlerType: (*HerdControlPlaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HerdControlPlane_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/proto/v1/herd.proto",
}
