name: Deploy Documentation

on:
  push:
    branches:
      - main
      - sn/building_docs
      
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-docs.txt'
      - '.github/workflows/docs.yml'

permissions:
  contents: write   # Crucial permission for mkdocs gh-deploy to push to gh-pages branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-docs.txt ]; then pip install -r requirements-docs.txt; else pip install mkdocs mkdocs-material; fi

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
